[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.1", default-features = false, features = ["derive"] }

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = { version = "0.2.99", default-features = false }
